services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/init:/docker-entrypoint-initdb.d:ro

  books:
    build: ./books
    env_file: [./books/.env]
    ports: ["8001:8001"]
    depends_on: [db]

  orders:
    build: ./orders
    env_file: [./orders/.env]
    ports: ["8082:8082"]
    depends_on: [db, books]

volumes:
  pgdata:
