global:
  scrape_interval: 30s
  evaluation_interval: 30s
  scrape_timeout: 10s
  external_labels:
    env: dev

rule_files:
  - /etc/prometheus/rules/*.yml

scrape_configs:
  - job_name: prometheus
    scrape_interval: 60s
    static_configs:
      - targets: [prometheus:9090]
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'prometheus_tsdb_.*|prometheus_engine_.*|prometheus_rule_.*'
        action: drop

  - job_name: orders
    scrape_interval: 30s
    scrape_timeout: 5s
    metrics_path: /metrics
    static_configs:
      - targets: [orders:8082]
    metric_relabel_configs:
      - source_labels: [handler]
        regex: '/health|/metrics'
        action: drop
