global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s
  external_labels:
    env: dev

rule_files:
  - /etc/prometheus/rules/*.yml

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: [prometheus:9090]
    relabel_configs:
      - source_labels: [job]
        target_label: service

  - job_name: otel-collector
    static_configs:
      - targets: [otel-collector:8889]
    relabel_configs:
      - source_labels: [job]
        target_label: service

  - job_name: books
    metrics_path: /metrics
    static_configs:
      - targets: [books:8001]
    relabel_configs:
      - source_labels: [job]
        target_label: service

  - job_name: orders
    metrics_path: /metrics
    static_configs:
      - targets: [orders:8082]
    relabel_configs:
      - source_labels: [job]
        target_label: service
